[package]
name = "kars"
version = "0.1.0"
authors = ["Angel ILIEV <a.v.iliev13@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3.4"

[[bench]]
name = "paths"
path = "benches/paths.rs"
harness = false
